# Generated by Django 2.0.4 on 2018-05-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloFPBajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFilter', models.CharField(max_length=200, verbose_name='Nombre Filtro')),
                ('imagePlantilla', models.ImageField(blank=True, null=True, upload_to='FPBajo', verbose_name='Imagen Plantilla')),
                ('Ap_db', models.FloatField(blank=True, default=None, null=True, verbose_name='Atenuacion en la banda de paso')),
                ('As_db', models.FloatField(blank=True, default=None, null=True, verbose_name='Atenuacion en la banda eliminada (stop)')),
                ('Fp_Hz', models.FloatField(blank=True, default=None, null=True, verbose_name='Frecuencia de paso')),
                ('Fs_Hz', models.FloatField(blank=True, default=None, null=True, verbose_name='Frecuencia de stop')),
                ('Rg_Ohm', models.FloatField(blank=True, default=None, null=True, verbose_name='Resistencia generador')),
                ('Rl_Ohm', models.FloatField(blank=True, default=None, null=True, verbose_name='Resistencia de carga (load)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'FPBajo',
                'verbose_name_plural': 'FPBajos',
                'ordering': ['-created'],
            },
        ),
    ]
