# Generated by Django 2.0.4 on 2018-05-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelofpbajo',
            name='tipoFiltro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de finalizacion'),
        ),
    ]
