# Generated by Django 2.0.4 on 2018-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelofpbajo',
            name='celery_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modelofpbajo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='Ap_db',
            field=models.FloatField(default=None, verbose_name='Atenuacion en la banda de paso [dB]'),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='As_db',
            field=models.FloatField(default=None, verbose_name='Atenuacion en la banda eliminada (stop) [dB]'),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='Fp_Hz',
            field=models.FloatField(default=None, verbose_name='Frecuencia de paso [Hz]'),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='Fs_Hz',
            field=models.FloatField(default=None, verbose_name='Frecuencia de stop [Hz]'),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='Rg_Ohm',
            field=models.FloatField(default=None, verbose_name='Resistencia generador [Ohm]'),
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='Rl_Ohm',
            field=models.FloatField(default=None, verbose_name='Resistencia de carga (load) [Ohm]'),
        ),
    ]
