# Generated by Django 2.0.4 on 2018-05-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0002_auto_20180529_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelofpbajo',
            name='author',
        ),
        migrations.AlterField(
            model_name='modelofpbajo',
            name='celery_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
