# Generated by Django 2.0.4 on 2018-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0002_auto_20180531_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro_Butterworth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenFiltro', models.IntegerField(verbose_name='Orden del Filtro')),
                ('g_1', models.FloatField()),
                ('g_2', models.FloatField()),
                ('g_3', models.FloatField()),
                ('g_4', models.FloatField()),
                ('g_5', models.FloatField()),
                ('g_6', models.FloatField()),
                ('g_7', models.FloatField()),
                ('g_8', models.FloatField()),
                ('g_9', models.FloatField()),
                ('g10', models.FloatField()),
            ],
        ),
    ]
