# Generated by Django 2.0.4 on 2018-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0006_auto_20180702_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro_Chebyshev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenFiltro', models.IntegerField(verbose_name='Orden del Filtro')),
                ('Rg', models.FloatField()),
                ('Rl', models.FloatField()),
                ('g_1', models.FloatField()),
                ('g_2', models.FloatField()),
                ('g_3', models.FloatField()),
                ('g_4', models.FloatField()),
                ('g_5', models.FloatField()),
                ('g_6', models.FloatField()),
                ('g_7', models.FloatField()),
                ('g_8', models.FloatField()),
                ('g_9', models.FloatField()),
                ('g_10', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='filtro_butterworth',
            name='Rg',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filtro_butterworth',
            name='Rl',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
