# Generated by Django 2.0.4 on 2018-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFPBajo', '0007_auto_20180703_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelofpbajo',
            name='imageDesnormalizadaFreImp',
            field=models.ImageField(blank=True, null=True, upload_to='FPBajo', verbose_name='Imagen Desnormalizada en Frecuencia e Impedancia'),
        ),
        migrations.AddField(
            model_name='modelofpbajo',
            name='imagePrototipoFiltro',
            field=models.ImageField(blank=True, null=True, upload_to='FPBajo', verbose_name='Imagen Prototipo Filtro'),
        ),
    ]
